/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zcds1_basObjectPageObjectPage journey");

        opaTest("Navigate to zcds1_basObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThezcds1_basList.onFilterBar().iExecuteSearch();

            Then.onThezcds1_basList.onTable().iCheckRows();
            When.onThezcds1_basList.onTable().iPressRow(0);

            Then.onThezcds1_basObjectPage.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThezcds1_basObjectPage.iCheckSection({ section: "GeneratedFacet1" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Vbeln" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Posnr" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Erdat" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Erzet" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Ernam" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Matnr" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Kunnr" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Waerk" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Netpr" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Netwr" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Kwmeng" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Vrkme" });
            Then.onThezcds1_basObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Maktx" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});